name: Discord Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Get diff of changes
      id: diff
      run: |
        git diff --name-only HEAD^ HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug output
      run: |
        echo "Changed files:"
        cat $GITHUB_EVENT_PATH
        echo "Diff output:"
        git diff
      if: steps.diff.outputs.files != ''

    - name: Send notification to Discord
      if: steps.diff.outputs.files != ''
      uses: Ilshidur/action-discord@master
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        color: '3066993'
        title: 'New commits in the repository'
        description: 'Changes were made to the following files:'
        fields: ${{ steps.diff.outputs.files }}
