name: Discord Notifications

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check if pull request
      run: echo "This is a pull request"
      if: github.event_name == 'pull_request' && github.event.pull_request.number != null

    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Get diff of changes
      id: diff
      run: |
        if [ -z "${{ github.event.inputs.from }}" ]; then
          from=main
        else
          from=${{ github.event.inputs.from }}
        fi
        git fetch --no-tags --depth=1 origin +refs/heads/${from}:refs/pull/${{ github.event.pull_request.number }}/head
        git diff --name-only FETCH_HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug output
      run: |
        echo "Changed files:"
        cat $GITHUB_EVENT_PATH
        echo "Diff output:"
        git diff
      if: steps.diff.outputs.files != ''

    - name: Send notification to Discord
      if: steps.diff.outputs.files != ''
      uses: Ilshidur/action-discord@master
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        color: '3066993'
        title: 'New commits in the repository'
        description: 'Changes were made to the following files:'
        fields: ${{ steps.diff.outputs.files }}
